apiVersion: v1
kind: Service
metadata:
  name: recommendations-v2
  labels:
    app: recommendations    
    version: v2
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: recommendations
    version: v2
