apiVersion: "config.istio.io/v1alpha2"
kind: listchecker
metadata:
  name: preferenceswhitelist
spec:
  overrides: ["recommendations"]
  blacklist: false
---
apiVersion: "config.istio.io/v1alpha2"
kind: listentry
metadata:
  name: preferencessource
spec:
  value: source.labels["app"]
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: checkfromcustomer
spec:
  match: destination.labels["app"] == "preferences"
  actions:
  - handler: preferenceswhitelist.listchecker
    instances:
    - preferencessource.listentry
