---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-circuitbreaker
  namespace: springistio
spec:
  source:
    name: preferences
    labels:
      app: preferences # all versions
  destination: 
    name: recommendations
    labels:
      app: recommendations # all versions
  loadBalancing:
    name: LEAST_CONN      
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 2m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100