---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-circuitbreaker
  namespace: tutorial
spec:
  source:
    namespace: tutorial
    name: preferences
  destination: 
    namespace: tutorial
    name: recommendations
  loadBalancing:
    name: RANDOM      
  circuitBreaker:
    simpleCb:
      httpConsecutiveErrors: 1
      sleepWindow: 2m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100