---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-loadbalancer
  namespace: springistio
spec:
  source:
    name: preferences
  destination: 
    name: recommendations
    labels:
      app: recommendations
  loadBalancing:
    name: RANDOM     
#    name: LEAST_CONN
#    name: ROUND_ROBIN
