---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-circuitbreaker
spec:
  destination: 
    namespace: tutorial
    name: recommendations
    labels:
      version: v2
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      sleepWindow: 2m      
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100      
      httpConsecutiveErrors: 1
#      httpMaxRequests: 1
      httpMaxRequestsPerConnection: 1
      


