---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-circuitbreaker
  namespace: springistio
spec:
  destination: 
    name: recommendations
    labels:
      app: recommendations
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxPendingRequests: 1
      httpConsecutiveErrors: 1
      sleepWindow: 1m
      httpDetectionInterval: 1s
      httpMaxEjectionPercent: 100