---
apiVersion: config.istio.io/v1alpha2
kind: DestinationPolicy
metadata:
  name: recommendations-circuitbreaker
spec:
  destination: 
    name: recommendations
    labels:
      version: v2
  circuitBreaker:
    simpleCb:
      maxConnections: 1
      httpMaxRequests: 1
      httpMaxRequestsPerConnection: 1
      sleepWindow: 30s
      httpDetectionInterval: 1s
