apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendation-mirror
spec:
  destination:
    namespace: tutorial
    name: recommendation
  precedence: 1
  route:
  - labels:
      version: v1
  mirror:
    namespace: tutorial
    name: recommendation-v2
    labels:
      version: v2
