apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-delay
spec:
  destination:
    name: recommendations
  precedence: 2
  route:
  - labels:
      app: recommendations
  httpFault:
    delay:
      percent: 50
      fixedDelay: 7s