apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-timeout
spec:
  destination:
    namespace: tutorial
    name: recommendations
  precedence: 1
  route:
  - labels:
      app: recommendations
  httpReqTimeout:
    simpleTimeout:
      timeout: 1s