apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-v2-503
spec:
  destination:
    namespace: tutorial
    name: recommendations
  precedence: 2
  route:
  - labels:
      version: v2
  httpFault:
    abort:
      percent: 50
      httpStatus: 503