apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-v1-v2
spec:
  destination:
    name: recommendations
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 75
  - labels:
      version: v2
    weight: 25