apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-mirror
spec:
  destination:
    name: recommendations
  precedence: 1
  route:
  - labels:
      version: v1
  mirror:
    name: recommendations-v2
    labels:
      version: v2