apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-v2-retry
spec:
  destination:
    name: recommendations
  precedence: 3
  route:
  - labels:
      version: v2
  httpReqRetries:
    simpleRetry:
      perTryTimeout: 2s
      attempts: 3