apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-default
spec:
  destination:
    namespace: tutorial
    name: recommendations
  precedence: 1
  route:
  - labels:
      version: v1
    weight: 100
