apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: recommendations-firefox
spec:
  destination:
    name: recommendations
  precedence: 2
  match:
    request:
      headers:
        user-agent:
          regex: ".*Firefox.*"  
  route:
  - labels:
      version: v2